---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(macleish)
library(sp)
library(rgeos)
library(leaflet)
library(rgdal)
```


```{r}
url <- "http://wsgw.mass.gov/data/gispub/shape/contours5k/hp337.zip"
download.file(url, destfile = basename(url))
unzip("hp337.zip", exdir = "WhatelyElevation")
dsn <- path.expand("WhatelyElevation")
wElevation <- readOGR(dsn, "hp337")
wElevation_4326 <- spTransform(wElevation, CRS("+init=epsg:4326"))


```

```{r}
url <- "http://wsgw.mass.gov/data/gispub/shape/contours5k/hp68.zip"
download.file(url, destfile = basename(url))
unzip("hp68.zip", exdir = "ConwayElevation")
dsn <- path.expand("ConwayElevation")
cElevation <- readOGR(dsn, "hp68")
cElevation_4326 <- spTransform(cElevation, CRS("+init=epsg:4326"))
```

```{r}
mac_boundry_4326 <- spTransform( macleish_layers[["boundary"]], CRS("+init=epsg:4326") )
mac_elevation_c <- gIntersection(mac_boundry_4326, cElevation_4326)
mac_elevation_w <- gIntersection(mac_boundry_4326, wElevation_4326)
mac_elevation <- gUnion (mac_elevation_w, mac_elevation_c)
trails_4326 <- spTransform(macleish_layers[["trails"]], CRS("+init=epsg:4326"))
```


```{r}
leaflet() %>%
  addTiles() %>%
  addPolylines(data = trails_4326 , weight = 1, color = "black")%>%
  addPolylines(data=mac_elevation, weight= 1, color="red")%>%
  addPolygons(data= mac_boundry_4326, weight = 1, color="blue")
```

```{r}
max_grade <- function(trailData){
  cTrail <- trailData@Lines[[1]]@coords ##%>%
              ##select("1", "2")
              #Line(ID = "a") %>%
             # list()%>%
              #Lines()%>%
             # SpatialLines()
  #proj4string(cTrail) <- CRS("+init=epsg:4326")
  #gIntersection(cTrail, wElevation_4326)
}

lapply(trails_4326@lines, max_grade)



get_elevation <- function(long, lat){
    
}
```


```{r}
##trail intersections with elevation lines

int_sect <- gIntersection(trails_4326, mac_elevation)

##elevation over intersection areas in Whately and Conway
int_pls <- over(trails_4326, wElevation_4326)
int_pls_c <- over(trails_4326, cElevation_4326)


```


```{r}
##Just NUMBER 12

trails_4326[9,]
leaflet() %>%
  addTiles() %>%
  addPolylines(data = trails_4326[9,] , weight = 3, color = "black")%>%
  addPolylines(data=mac_elevation, weight= 1, color="red")%>%
  addPolygons(data= mac_boundry_4326, weight = 1, color="blue")%>%
  addMarkers(lng = -72.68063, lat = 42.45033) %>%
  addMarkers(lng = -72.67783, lat =  42.45667)

```

```{r}

new_intersection <- gIntersection(trails_4326[9,], cElevation_4326)
int_pls_pract <- over(new_intersection, cElevation_4326)

int_pls_c <- over(trails_4326[9,], cElevation_4326, returnList = TRUE) %>% as.data.frame()
int_pls_w <- over(trails_4326[9,], wElevation_4326, returnList =  TRUE) %>% as.data.frame()

int_pls_totl <- rbind(int_pls_c, int_pls_w) %>% na.omit() %>% summarize(elevation = max(ELEV_FT) - min(ELEV_FT))


```


